### ISSUE TITLE
Avoid multiple generation of identical interceptor method body

### ISSUE THREAD

**Issue by Gh0stWalk3r** [FlashOWare/FlashOWare.Generators#9]
Hello Stefan,
I watched your YouTube video and tried your library.
When I looked at the generated code I noticed that it generates the same method body for the interceptor multiple times (for each invocation). I think it is enough to generate the (unique) method body once and just apply the interceptor attribute multiple times.

Kind regards,
Gregor

**Comment by Flash0ver** [comment]
Hello Gregor!

For posterity: the YouTube video: [Experimental C# Interceptors: AOT & Performance for free | .NET Conf 2023](https://www.youtube.com/watch?v=wadfRRrEOh4)

I actually had this issue on my "local backlog" for the next _pre-release_. I've now GitHub Issue-ified all items from my "local backlog".

Thank you very much for trying out this Generator package ... and thank you for your feedback to improve the performance of the experimental Interceptor-Generator. I appreciate it!
